server {
    listen 8080;

    # FRONTEND React
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # BACKEND: VENTAS
    location /api/v1/ventas {
        proxy_pass http://10.0.8.41:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # BACKEND: DESPACHOS
    location /api/v1/despachos {
        proxy_pass http://10.0.8.41:8082;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}